name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Clean temp files to avoid exit 28
        run: |
          sudo rm -rf /tmp/*
          sudo apt-get clean

      - name: Analyse only main code folder with pylint
        run: |
          # Replace 'testing/' with your main code folder
          pylint $(git ls-files 'testing/*.py')
# name: Pylint

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: ["3.8", "3.9", "3.10"]
#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v3
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pylint
#     - name: Analysing the code with pylint
#       run: |
#         pylint $(git ls-files '*.py')
